"""Paper attribution tables generated from configs/datasets.yaml (T10).

Emits two booktabs LaTeX fragments into reports/ so the registry stays the
single source of truth for sources, licenses, and label mappings:

- ``tab_label_mapping.tex``: source label -> target class, grouped by source,
  with DROP labels shown (they feed the open-set wilderness probe pool).
- ``tab_dataset_licenses.tex``: source, images, license, role, attribution,
  plus the excluded-with-reason footnote table per T10.

Image counts are census figures (F17/F18, verified 2026-06-10); the pipeline
re-counts everything it ingests. Regenerate with::

    python -m trashmonkey.data.attribution
"""

from __future__ import annotations

from pathlib import Path

from trashmonkey.data.download.registry import DROP, SourceSpec, load_registry
from trashmonkey.utils.config import Config, load_config

REPO_ROOT = Path(__file__).resolve().parents[3]
DATASETS_PATH = REPO_ROOT / "configs" / "datasets.yaml"

GENERATED_HEADER = (
    "% Auto-generated by trashmonkey.data.attribution -- do not edit by hand.\n"
    "% Source of truth: configs/datasets.yaml. Regenerate with:\n"
    "%   python -m trashmonkey.data.attribution\n"
)

# Census image counts (F17/F18, file enumeration 2026-06-10). Paper-table
# context only -- the pipeline re-counts on ingest and the manifest wins.
CENSUS_IMAGE_COUNTS: dict[str, int] = {
    "trashnet": 2_527,
    "drinking-waste": 4_828,
    "garbage-detection": 10_464,
    "alistairking-household": 15_000,
    "realwaste": 4_752,
}

# QA-reference rows: never ingested into training; used only as the IoU
# cross-check reference for auto-boxing QA (T3). (source, images, license,
# attribution).
QA_REFERENCES: tuple[tuple[str, int, str, str], ...] = (
    (
        "trashnet-bbox (Polygence)",
        2_524,
        "CC BY 4.0",
        "Polygence, human-annotated TrashNet bounding boxes (Roboflow Universe), "
        "IoU cross-check reference for auto-boxing QA only (T3)",
    ),
)

# Excluded-with-reason footnote table (T10). (source, exclusion reason).
EXCLUDED_SOURCES: tuple[tuple[str, str], ...] = (
    ("WaDaBa", "contract-gated access; plastics-only and PET-dominated"),
    ("mostafaabla/garbage-classification", "ODbL license; TrashNet-repack lineage (F20)"),
    (
        "sumn2u/garbage-classification-v2",
        "license ambiguity (MIT page vs CC BY 4.0 paper) and conflicting published counts",
    ),
    ("ZeroWaste", "CC BY-NC (non-commercial) license"),
    ("TACO", "cluttered-scene domain mismatch (F19); per-image Flickr licenses"),
    ("CompostNet", "no license published"),
    (
        "techsash/waste-classification, Fruits-360",
        "CC BY-SA; off-domain; held as organic reserve only (F21)",
    ),
)

# Single-pass character map: replacements must not be re-escaped (the braces
# in \textbackslash{} would otherwise be mangled by a sequential replace).
_LATEX_MAP = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(text: str) -> str:
    """Escape LaTeX special characters in plain text (single pass)."""
    return "".join(_LATEX_MAP.get(char, char) for char in text)


def _format_count(count: int) -> str:
    return f"{count:,}".replace(",", "{,}")


def _grouped_targets(spec: SourceSpec) -> list[tuple[str, list[str]]]:
    """Mapping rows compressed to (target, [labels]) in first-appearance order, DROP last."""
    order: list[str] = []
    grouped: dict[str, list[str]] = {}
    for label, target in spec.mapping.items():
        if target not in grouped:
            grouped[target] = []
            order.append(target)
        grouped[target].append(label)
    if DROP in order:
        order.remove(DROP)
        order.append(DROP)
    return [(target, grouped[target]) for target in order]


def render_label_mapping(registry: dict[str, SourceSpec]) -> str:
    """LaTeX fragment: per-source label -> target class table (T1)."""
    lines = [
        GENERATED_HEADER,
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Label mapping from source taxonomies onto the six target classes",
        r"    (T1). \textsc{drop} labels never enter training; they are routed to the",
        r"    open-set wilderness probe pool (T9).}",
        r"  \label{tab:label-mapping}",
        r"  \small",
        r"  \begin{tabular}{llp{6.8cm}}",
        r"    \toprule",
        r"    Source & Target class & Source labels \\",
    ]
    for spec in registry.values():
        lines.append(r"    \midrule")
        source_cell = latex_escape(spec.name)
        for target, labels in _grouped_targets(spec):
            target_cell = r"\textsc{drop}" if target == DROP else latex_escape(target)
            labels_cell = ", ".join(latex_escape(label) for label in labels)
            lines.append(f"    {source_cell} & {target_cell} & {labels_cell} \\\\")
            source_cell = ""
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines) + "\n"


def _census_count(name: str) -> int:
    if name not in CENSUS_IMAGE_COUNTS:
        raise ValueError(
            f"no census image count for source '{name}'; "
            "add it to CENSUS_IMAGE_COUNTS in trashmonkey.data.attribution"
        )
    return CENSUS_IMAGE_COUNTS[name]


def _role(name: str, leave_out_source: str | None) -> str:
    return "test" if name == leave_out_source else "train"


def render_dataset_licenses(registry: dict[str, SourceSpec], leave_out_source: str | None) -> str:
    """LaTeX fragment: license/attribution table plus excluded-sources table (T10)."""
    lines = [
        GENERATED_HEADER,
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Data sources: census image counts (the pipeline re-counts on",
        r"    ingest), licenses, and roles (T2/T6/T10). The test source is the",
        r"    leave-one-source-out TEST-1 holdout: ingested, never trained on.",
        r"    The qa-ref source is used only as an IoU cross-check reference for",
        r"    auto-box QA (T3).}",
        r"  \label{tab:dataset-licenses}",
        r"  \small",
        r"  \begin{tabular}{lrllp{5.2cm}}",
        r"    \toprule",
        r"    Source & Images & License & Role & Attribution \\",
        r"    \midrule",
    ]
    for spec in registry.values():
        lines.append(
            f"    {latex_escape(spec.name)} & {_format_count(_census_count(spec.name))} & "
            f"{latex_escape(spec.license)} & {_role(spec.name, leave_out_source)} & "
            f"{latex_escape(spec.attribution)} \\\\"
        )
    for name, images, license_name, attribution in QA_REFERENCES:
        lines.append(
            f"    {latex_escape(name)} & {_format_count(images)} & "
            f"{latex_escape(license_name)} & qa-ref & {latex_escape(attribution)} \\\\"
        )
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
        "",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Sources surveyed by the dataset census and excluded, with",
        r"    reasons (T10).}",
        r"  \label{tab:excluded-sources}",
        r"  \small",
        r"  \begin{tabular}{lp{8.2cm}}",
        r"    \toprule",
        r"    Source & Exclusion reason \\",
        r"    \midrule",
    ]
    for name, reason in EXCLUDED_SOURCES:
        lines.append(f"    {latex_escape(name)} & {latex_escape(reason)} \\\\")
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines) + "\n"


def write_tables(repo_root: Path | None = None, config: Config | None = None) -> tuple[Path, Path]:
    """Render both fragments from the real registry and write them under reports/."""
    root = REPO_ROOT if repo_root is None else repo_root
    cfg = load_config() if config is None else config
    registry = load_registry(root / "configs" / "datasets.yaml", cfg.classes)
    reports_dir = root / cfg.paths.reports
    reports_dir.mkdir(parents=True, exist_ok=True)
    mapping_path = reports_dir / "tab_label_mapping.tex"
    licenses_path = reports_dir / "tab_dataset_licenses.tex"
    mapping_path.write_text(render_label_mapping(registry))
    licenses_path.write_text(render_dataset_licenses(registry, cfg.eval.leave_out_source))
    return mapping_path, licenses_path


def main() -> None:
    """CLI entry point: regenerate both fragments and print their paths."""
    for path in write_tables():
        print(path)


if __name__ == "__main__":
    main()
