"""Publication figures (task 014); ``plots`` is the stable import surface."""

from yolo_waste_sorter.visualization.plots import (
    CURVE_ARRAYS,
    DPI,
    LABEL_SIZE,
    MAX_WRONG_BIN,
    PALETTE,
    SWEEP_COLUMNS,
    TICK_SIZE,
    CurveArrays,
    PlotError,
    SweepRow,
    finalize,
    load_curves_npz,
    pareto_front,
    plot_dataset_composition,
    plot_per_class_curves,
    plot_severity_curve,
    plot_threshold_tradeoff,
    read_split_composition,
    read_sweep_csv,
    resolve_report,
    series_colors,
    setup_style,
)

__all__ = [
    "CURVE_ARRAYS",
    "DPI",
    "LABEL_SIZE",
    "MAX_WRONG_BIN",
    "PALETTE",
    "SWEEP_COLUMNS",
    "TICK_SIZE",
    "CurveArrays",
    "PlotError",
    "SweepRow",
    "finalize",
    "load_curves_npz",
    "pareto_front",
    "plot_dataset_composition",
    "plot_per_class_curves",
    "plot_severity_curve",
    "plot_threshold_tradeoff",
    "read_split_composition",
    "read_sweep_csv",
    "resolve_report",
    "series_colors",
    "setup_style",
]
